- name: root
  description: Something changes monorepo root
  color: 73c0ff

- name: design-system
  description: Something changes in design-system package
  color: 35a2b3

- name: eslint-config
  description: Something changes in eslint-config package
  color: 4b32c2

- name: prettier-config
  description: Something changes in prettier-config package
  color: efb43b
