root:
  - "*"

workflows:
  - .github/workflows/*

design-system:
  - packages/design-system/**/*

eslint-config:
  - packages/eslint-config/**/*

prettier-config:
  - packages/prettier-config/**/*

design-system-demo:
  - web/design-system-demo/**/*
