import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Almost before we knew it, we had left the ground.</h1>
      <h2>Almost before we knew it, we had left the ground.</h2>
      <h3>Almost before we knew it, we had left the ground.</h3>
      <h4>Almost before we knew it, we had left the ground.</h4>
      <h5>Almost before we knew it, we had left the ground.</h5>
      <h6>Almost before we knew it, we had left the ground.</h6>
    </div>
  )
}

export default Home
