name: Deploy design-system-demo preview site

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    branches:
      - main
    paths:
      - web/design-system-demo/**

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            :rocket:  Preview site deployment is preparing
            <!-- PR_AUTO_PREVIEW -->
          body-include: "<!-- PR_AUTO_PREVIEW -->"

  deploy:
    name: Build & Deploy Preview Site
    runs-on: ubuntu-latest
    needs: setup
    if: always() && needs.setup.result != 'failure'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install dependencies
        working-directory: web/design-system-demo
        run: yarn install --immutable-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build
        working-directory: web/design-system-demo
        run: yarn static

      - name: Deploy preview site to Surge
        working-directory: web/design-system-demo
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.event.number }}-dsd.surge.sh
          npx surge --project ./build --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: preview-site-artifact
          path: web/design-system-demo/static/
          retention-days: 3

  post-deploy:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    needs: deploy
    if: always() && needs.deploy.result != 'failure'

    steps:
      - name: Update comment status
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [:white_check_mark:  Preview site deployment succeeded](https://dsd-${{ github.event.number }}-preview.surge.sh)
            <!-- PR_AUTO_PREVIEW -->
          body-include: "<!-- PR_AUTO_PREVIEW -->"

      - name: The job has failed
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            :x:  Preview site deployment failed
            <!-- PR_AUTO_PREVIEW -->
          body-include: "<!-- PR_AUTO_PREVIEW -->"
