name: Label PR

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  triage:
    name: Triage PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
