name: Publish Prettier config

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/prettier-config/**

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: https://npm.pkg.github.com/
          package: packages/prettier-config/package.json

      - name: Create tag
        if: steps.publish.outputs.type != 'none'
        uses: actions/github-script@v6
        env:
          NEXT_VERSION: ${{ steps.publish.outputs.version }}
        with:
          script: |
            const newTag = `prettier-config-v${process.env.NEXT_VERSION}`

            try {
              core.debug(`Tagging #${context.sha} with tag ${newTag}`);

              console.log(github)

              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${newTag}`,
                sha: context.sha
              })
            } catch (error) {
              core.error(error);
              core.setFailed(error.message);
            }

      - name: Create Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: 6thpath/action-github-release@v1
        with:
          tag_name: prettier-config-v${{ steps.publish.outputs.version }}
          body: |
            Version ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false

      - name: Log release URL
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.url }}"
