name: Publish Design System

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/design-system/**

jobs:
  Publish-Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepublish actions
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
        working-directory: packages/design-system
        env:
          NPM_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - run: yarn compile
        working-directory: packages/design-system

      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          registry: https://npm.pkg.github.com/
          package: packages/design-system/package.json

      - name: Create tag
        if: steps.publish.outputs.type != 'none'
        uses: actions/github-script@v4
        env:
          NEXT_VERSION: ${{ steps.publish.outputs.version }}
        with:
          script: |
            const newTag = `design-system-v${process.env.NEXT_VERSION}`

            try {
              core.debug(`Tagging #${context.sha} with tag ${newTag}`);

              github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${newTag}`,
                sha: context.sha
              })
            } catch (error) {
              core.error(error);
              core.setFailed(error.message);
            }

      - name: Create Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: design-system-v${{ steps.publish.outputs.version }}
          body: |
            Version ${{ steps.publish.outputs.version }}
          draft: true
          prerelease: false

      - name: Log release URL
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.url }}"
