name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
